services:
  web:
    image: sylvaingauthier2pro/p13_python-oc-lettings-fr:latest
    environment:
      - DEBUG=0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    restart: "on-failure"