# Generated by Django 3.0 on 2023-06-08 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0002_auto_20230606_2213'),
        ('lettings', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            "INSERT INTO lettings_address SELECT * FROM oc_lettings_site_address;"
            "INSERT INTO lettings_letting SELECT * FROM oc_lettings_site_letting;"
            "INSERT INTO profiles_profile SELECT * FROM oc_lettings_site_profile;"
        ),
        migrations.RemoveField(
            model_name='letting',
            name='address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Letting',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
