name: Django CI/CD Master

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Linting
      run: |
        flake8
    - name: Run Tests
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        DEBUG: 0
      run: |
        pytest

    - name: Build and Push to DockerHub
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: sylvaingauthier2pro/p13_python-oc-lettings-fr
        buildArgs: |
          git_hash=$(git rev-parse --short "$GITHUB_SHA"),
          git_branch=${GITHUB_REF#refs/heads/}
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - id: deploy
      uses: bitovi/github-actions-deploy-docker-to-ec2@v0.5.4
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_default_region: us-east-1
        dot_env: ${{ secrets.DOT_ENV }}